[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
evm_version = "cancun"

remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "account-abstraction/=lib/account-abstraction/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"
